// generated by lengc (js backend) from for2ybv4p1.c.nif
"use strict";

let X60QiniGuard_0_for2ybv4p1 = allocFixed(1);

function X60Qini_0_for2ybv4p1() {
  if (mem.u8At(X60QiniGuard_0_for2ybv4p1)) {
    return;
  }
  mem.setU8(X60QiniGuard_0_for2ybv4p1, true);
  X60Qini_0_sysvq0asl();
}
