// generated by lengc (js backend) from jsfc0lwq21.c.nif
"use strict";

function eQdestroy_0_jsfc0lwq21(x_2) {
  _jsRelease(mem.i32(x_2));
}

function eqQ_0_jsfc0lwq21(a_5, b_4) {
  let result_1;
  let X60Qx_2 = _jsStrictEq(mem.i32(a_5), mem.i32(b_4));
  result_1 = X60Qx_2;
  return result_1;
}

function isNil_0_jsfc0lwq21(v_3) {
  let result_2;
  result_2 = (mem.i32(v_3) === 0);
  return result_2;
}

function toJs_0_jsfc0lwq21(x_4) {
  let result_6 = allocFixed(4);
  eQdestroy_0_jsfc0lwq21(result_6);
  let X60Qx_4 = _numToJs(x_4);
  mem.copy(result_6, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_4);
    return _o;
  })(), 4);
  return result_6;
}

function toInt_0_jsfc0lwq21(v_5) {
  let result_7;
  let X60Qx_5 = _jsToNum(mem.i32(v_5));
  result_7 = X60Qx_5;
  return result_7;
}

function toJs_2_jsfc0lwq21(b_5) {
  let result_10 = allocFixed(4);
  eQdestroy_0_jsfc0lwq21(result_10);
  let X60Qx_8 = _boolToJs(b_5);
  mem.copy(result_10, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_8);
    return _o;
  })(), 4);
  return result_10;
}

function toBool_0_jsfc0lwq21(v_7) {
  let result_11;
  let X60Qx_9 = _jsToBool(mem.i32(v_7));
  result_11 = X60Qx_9;
  return result_11;
}

function toJs_3_jsfc0lwq21(s_0) {
  let result_12 = allocFixed(4);
  let t_0 = allocFixed(8);
  mem.copy(t_0, nimStrDup(s_0), 8);
  eQdestroy_0_jsfc0lwq21(result_12);
  let X60Qx_10 = toCString_0_sysvq0asl(t_0);
  let X60Qx_11 = len_4_sysvq0asl(t_0);
  let X60Qx_12 = _strToJs(X60Qx_10, X60Qx_11);
  mem.copy(result_12, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_12);
    return _o;
  })(), 4);
  nimStrDestroy(t_0);
  return result_12;
  nimStrDestroy(t_0);
  return result_12;
}

function toStr_0_jsfc0lwq21(v_8) {
  let result_13 = allocFixed(8);
  nimStrWasMoved(result_13);
  let n_1 = _jsStrLen(mem.i32(v_8));
  if ((n_1 <= 0)) {
    return (() => {
      let _o = allocFixed(8);
      mem.setU32(_o, 0);
      mem.setU32((_o + 4), 0);
      return _o;
    })();
  }
  nimStrDestroy(result_13);
  let X60Qx_13 = allocFixed(8);
  mem.copy(X60Qx_13, newString_0_sysvq0asl(n_1), 8);
  mem.copy(result_13, X60Qx_13, 8);
  let X60Qx_14 = toCString_0_sysvq0asl(result_13);
  _jsStrInto(mem.i32(v_8), X60Qx_14);
  return result_13;
}

function newJsObject_0_jsfc0lwq21() {
  let result_15 = allocFixed(4);
  eQdestroy_0_jsfc0lwq21(result_15);
  let X60Qx_16 = _jsNewObject();
  mem.copy(result_15, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_16);
    return _o;
  })(), 4);
  return result_15;
}

function global_0_jsfc0lwq21(name_8) {
  let result_21 = allocFixed(4);
  let n_2 = allocFixed(4);
  mem.copy(n_2, toJs_3_jsfc0lwq21(name_8), 4);
  eQdestroy_0_jsfc0lwq21(result_21);
  let X60Qx_22 = _jsGlobalH(mem.i32(n_2));
  mem.copy(result_21, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_22);
    return _o;
  })(), 4);
  eQdestroy_0_jsfc0lwq21(n_2);
  return result_21;
  eQdestroy_0_jsfc0lwq21(n_2);
  return result_21;
}

function get_0_jsfc0lwq21(obj_8, name_9) {
  let result_22 = allocFixed(4);
  let n_3 = allocFixed(4);
  mem.copy(n_3, toJs_3_jsfc0lwq21(name_9), 4);
  eQdestroy_0_jsfc0lwq21(result_22);
  let X60Qx_23 = _jsGetProp(mem.i32(obj_8), mem.i32(n_3));
  mem.copy(result_22, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_23);
    return _o;
  })(), 4);
  eQdestroy_0_jsfc0lwq21(n_3);
  return result_22;
  eQdestroy_0_jsfc0lwq21(n_3);
  return result_22;
}

function set_0_jsfc0lwq21(obj_9, name_10, val_3) {
  let n_4 = allocFixed(4);
  mem.copy(n_4, toJs_3_jsfc0lwq21(name_10), 4);
  _jsSetProp(mem.i32(obj_9), mem.i32(n_4), mem.i32(val_3));
  eQdestroy_0_jsfc0lwq21(n_4);
}

function call_1_jsfc0lwq21(obj_11, name_12, a_6) {
  let result_24 = allocFixed(4);
  let n_6 = allocFixed(4);
  mem.copy(n_6, toJs_3_jsfc0lwq21(name_12), 4);
  eQdestroy_0_jsfc0lwq21(result_24);
  let X60Qx_25 = _jsCall1(mem.i32(obj_11), mem.i32(n_6), mem.i32(a_6));
  mem.copy(result_24, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_25);
    return _o;
  })(), 4);
  eQdestroy_0_jsfc0lwq21(n_6);
  return result_24;
  eQdestroy_0_jsfc0lwq21(n_6);
  return result_24;
}

function call_2_jsfc0lwq21(obj_12, name_13, a_7, b_6) {
  let result_25 = allocFixed(4);
  let n_7 = allocFixed(4);
  mem.copy(n_7, toJs_3_jsfc0lwq21(name_13), 4);
  eQdestroy_0_jsfc0lwq21(result_25);
  let X60Qx_26 = _jsCall2(mem.i32(obj_12), mem.i32(n_7), mem.i32(a_7), mem.i32(b_6));
  mem.copy(result_25, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_26);
    return _o;
  })(), 4);
  eQdestroy_0_jsfc0lwq21(n_7);
  return result_25;
  eQdestroy_0_jsfc0lwq21(n_7);
  return result_25;
}

function call_3_jsfc0lwq21(obj_13, name_14, a_8, b_7, c_1) {
  let result_26 = allocFixed(4);
  let n_8 = allocFixed(4);
  mem.copy(n_8, toJs_3_jsfc0lwq21(name_14), 4);
  eQdestroy_0_jsfc0lwq21(result_26);
  let X60Qx_27 = _jsCall3(mem.i32(obj_13), mem.i32(n_8), mem.i32(a_8), mem.i32(b_7), mem.i32(c_1));
  mem.copy(result_26, (() => {
    let _o = allocFixed(4);
    mem.setI32(_o, X60Qx_27);
    return _o;
  })(), 4);
  eQdestroy_0_jsfc0lwq21(n_8);
  return result_26;
  eQdestroy_0_jsfc0lwq21(n_8);
  return result_26;
}

function inc_1_I6wjjge_jsfc0lwq21(x_11) {
  mem.setI32(x_11, (mem.i32(x_11) + 1));
}

let X60QiniGuard_0_jsfc0lwq21 = allocFixed(1);

function X60Qini_0_jsfc0lwq21() {
  if (mem.u8At(X60QiniGuard_0_jsfc0lwq21)) {
    return;
  }
  mem.setU8(X60QiniGuard_0_jsfc0lwq21, true);
  X60Qini_0_sysvq0asl();
}
