// generated by lengc (js backend) from syn1lfpjv.c.nif
"use strict";

let strlit_0_I8572766038233537570_syn1lfpjv = allocFixed(16);

mem.setI32(strlit_0_I8572766038233537570_syn1lfpjv, 4);

mem.setI32((strlit_0_I8572766038233537570_syn1lfpjv + 4), 0);

mem.setI32((strlit_0_I8572766038233537570_syn1lfpjv + 8), 0);

mem.writeStr((strlit_0_I8572766038233537570_syn1lfpjv + 12), "true");

let strlit_0_I3372626016653902757_syn1lfpjv = allocFixed(17);

mem.setI32(strlit_0_I3372626016653902757_syn1lfpjv, 5);

mem.setI32((strlit_0_I3372626016653902757_syn1lfpjv + 4), 0);

mem.setI32((strlit_0_I3372626016653902757_syn1lfpjv + 8), 0);

mem.writeStr((strlit_0_I3372626016653902757_syn1lfpjv + 12), "false");

function write_0_syn1lfpjv(f_4, s_0) {
  let X60Qx_1 = readRawData_0_sysvq0asl(s_0, 0);
  let X60Qx_2 = len_4_sysvq0asl(s_0);
  let X60Qx_3 = fwrite(X60Qx_1, 1, X60Qx_2, f_4);
}

function write_7_syn1lfpjv(f_11, c_1) {
  let X60Qx_4 = fputc(c_1, f_11);
}

let X60QiniGuard_0_syn1lfpjv = allocFixed(1);

function X60Qini_0_syn1lfpjv() {
  if (mem.u8At(X60QiniGuard_0_syn1lfpjv)) {
    return;
  }
  mem.setU8(X60QiniGuard_0_syn1lfpjv, true);
  X60Qini_0_sysvq0asl();
  X60Qini_0_for2ybv4p1();
}
