// generated by lengc (js backend) from tff8wodtr.c.nif
"use strict";

let strlit_0_I4512127154334175537_tff8wodtr = allocFixed(19);

mem.setI32(strlit_0_I4512127154334175537_tff8wodtr, 7);

mem.setI32((strlit_0_I4512127154334175537_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I4512127154334175537_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I4512127154334175537_tff8wodtr + 12), "console");

let strlit_0_I5853397530369228807_tff8wodtr = allocFixed(51);

mem.setI32(strlit_0_I5853397530369228807_tff8wodtr, 39);

mem.setI32((strlit_0_I5853397530369228807_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I5853397530369228807_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I5853397530369228807_tff8wodtr + 12), "hello from Nim through a real JS string");

let strlit_0_I12935728853510326435_tff8wodtr = allocFixed(16);

mem.setI32(strlit_0_I12935728853510326435_tff8wodtr, 4);

mem.setI32((strlit_0_I12935728853510326435_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I12935728853510326435_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I12935728853510326435_tff8wodtr + 12), "Math");

let strlit_0_I2301975825215568994_tff8wodtr = allocFixed(32);

mem.setI32(strlit_0_I2301975825215568994_tff8wodtr, 20);

mem.setI32((strlit_0_I2301975825215568994_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I2301975825215568994_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I2301975825215568994_tff8wodtr + 12), "Math.max(3, 7)    = ");

let strlit_0_I6208868947491189530_tff8wodtr = allocFixed(32);

mem.setI32(strlit_0_I6208868947491189530_tff8wodtr, 20);

mem.setI32((strlit_0_I6208868947491189530_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I6208868947491189530_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I6208868947491189530_tff8wodtr + 12), "Math.max(3, 7, 5) = ");

let strlit_0_I12805258542531914732_tff8wodtr = allocFixed(22);

mem.setI32(strlit_0_I12805258542531914732_tff8wodtr, 10);

mem.setI32((strlit_0_I12805258542531914732_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I12805258542531914732_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I12805258542531914732_tff8wodtr + 12), "round-trip");

let strlit_0_I15421062535947656287_tff8wodtr = allocFixed(25);

mem.setI32(strlit_0_I15421062535947656287_tff8wodtr, 13);

mem.setI32((strlit_0_I15421062535947656287_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I15421062535947656287_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I15421062535947656287_tff8wodtr + 12), "back in Nim: ");

let strlit_0_I834269026986168554_tff8wodtr = allocFixed(18);

mem.setI32(strlit_0_I834269026986168554_tff8wodtr, 6);

mem.setI32((strlit_0_I834269026986168554_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I834269026986168554_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I834269026986168554_tff8wodtr + 12), "nimony");

let strlit_0_I407209193152762291_tff8wodtr = allocFixed(16);

mem.setI32(strlit_0_I407209193152762291_tff8wodtr, 4);

mem.setI32((strlit_0_I407209193152762291_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I407209193152762291_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I407209193152762291_tff8wodtr + 12), "name");

let strlit_0_I6393444175955872624_tff8wodtr = allocFixed(16);

mem.setI32(strlit_0_I6393444175955872624_tff8wodtr, 4);

mem.setI32((strlit_0_I6393444175955872624_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I6393444175955872624_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I6393444175955872624_tff8wodtr + 12), "year");

let strlit_0_I6644378417582681152_tff8wodtr = allocFixed(29);

mem.setI32(strlit_0_I6644378417582681152_tff8wodtr, 17);

mem.setI32((strlit_0_I6644378417582681152_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I6644378417582681152_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I6644378417582681152_tff8wodtr + 12), "o.year via get = ");

let strlit_0_I6373137695046429832_tff8wodtr = allocFixed(16);

mem.setI32(strlit_0_I6373137695046429832_tff8wodtr, 4);

mem.setI32((strlit_0_I6373137695046429832_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I6373137695046429832_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I6373137695046429832_tff8wodtr + 12), "JSON");

let strlit_0_I7519307887382905868_tff8wodtr = allocFixed(21);

mem.setI32(strlit_0_I7519307887382905868_tff8wodtr, 9);

mem.setI32((strlit_0_I7519307887382905868_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I7519307887382905868_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I7519307887382905868_tff8wodtr + 12), "stringify");

let strlit_0_I14551632781070332322_tff8wodtr = allocFixed(29);

mem.setI32(strlit_0_I14551632781070332322_tff8wodtr, 17);

mem.setI32((strlit_0_I14551632781070332322_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I14551632781070332322_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I14551632781070332322_tff8wodtr + 12), "bool round-trip: ");

let strlit_0_I933664836153361417_tff8wodtr = allocFixed(16);

mem.setI32(strlit_0_I933664836153361417_tff8wodtr, 4);

mem.setI32((strlit_0_I933664836153361417_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I933664836153361417_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I933664836153361417_tff8wodtr + 12), "nope");

let strlit_0_I6074055191300679588_tff8wodtr = allocFixed(32);

mem.setI32(strlit_0_I6074055191300679588_tff8wodtr, 20);

mem.setI32((strlit_0_I6074055191300679588_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I6074055191300679588_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I6074055191300679588_tff8wodtr + 12), "missing prop isNil: ");

let strlit_0_I11663264536865316071_tff8wodtr = allocFixed(27);

mem.setI32(strlit_0_I11663264536865316071_tff8wodtr, 15);

mem.setI32((strlit_0_I11663264536865316071_tff8wodtr + 4), 0);

mem.setI32((strlit_0_I11663264536865316071_tff8wodtr + 8), 0);

mem.writeStr((strlit_0_I11663264536865316071_tff8wodtr + 12), "self === self: ");

let console_0_tff8wodtr = allocFixed(4);

let m_0_tff8wodtr = allocFixed(4);

let o_0_tff8wodtr = allocFixed(4);

let X60QiniGuard_0_tff8wodtr = allocFixed(1);

function X60Qini_0_tff8wodtr() {
  if (mem.u8At(X60QiniGuard_0_tff8wodtr)) {
    return;
  }
  mem.setU8(X60QiniGuard_0_tff8wodtr, true);
  X60Qini_0_sysvq0asl();
  X60Qini_0_syn1lfpjv();
  X60Qini_0_jsfc0lwq21();
  mem.copy(console_0_tff8wodtr, global_0_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1852793854);
    mem.setU32((_o + 4), strlit_0_I4512127154334175537_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qtmp_1 = allocFixed(4);
  mem.copy(X60Qtmp_1, toJs_3_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1818585342);
    mem.setU32((_o + 4), strlit_0_I5853397530369228807_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qtmp_0 = allocFixed(4);
  mem.copy(X60Qtmp_0, call_1_jsfc0lwq21(console_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1735355395);
    mem.setU32((_o + 4), 0);
    return _o;
  })(), X60Qtmp_1), 4);
  let X60Qx_0 = allocFixed(4);
  mem.copy(X60Qx_0, X60Qtmp_0, 4);
  mem.copy(m_0_tff8wodtr, global_0_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1952534014);
    mem.setU32((_o + 4), strlit_0_I12935728853510326435_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qtmp_5 = allocFixed(4);
  mem.copy(X60Qtmp_5, toJs_0_jsfc0lwq21(3), 4);
  let X60Qtmp_6 = allocFixed(4);
  mem.copy(X60Qtmp_6, toJs_0_jsfc0lwq21(7), 4);
  let X60Qtmp_4 = allocFixed(4);
  mem.copy(X60Qtmp_4, call_2_jsfc0lwq21(m_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 2019650819);
    mem.setU32((_o + 4), 0);
    return _o;
  })(), X60Qtmp_5, X60Qtmp_6), 4);
  let X60Qx_1 = toInt_0_jsfc0lwq21(X60Qtmp_4);
  let X60Qtmp_3 = allocFixed(8);
  mem.copy(X60Qtmp_3, dollarQ_2_sysvq0asl(X60Qx_1), 8);
  let X60Qtmp_2 = allocFixed(8);
  mem.copy(X60Qtmp_2, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1952534014);
    mem.setU32((_o + 4), strlit_0_I2301975825215568994_tff8wodtr);
    return _o;
  })(), X60Qtmp_3), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_2);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_10 = allocFixed(4);
  mem.copy(X60Qtmp_10, toJs_0_jsfc0lwq21(3), 4);
  let X60Qtmp_11 = allocFixed(4);
  mem.copy(X60Qtmp_11, toJs_0_jsfc0lwq21(7), 4);
  let X60Qtmp_12 = allocFixed(4);
  mem.copy(X60Qtmp_12, toJs_0_jsfc0lwq21(5), 4);
  let X60Qtmp_9 = allocFixed(4);
  mem.copy(X60Qtmp_9, call_3_jsfc0lwq21(m_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 2019650819);
    mem.setU32((_o + 4), 0);
    return _o;
  })(), X60Qtmp_10, X60Qtmp_11, X60Qtmp_12), 4);
  let X60Qx_2 = toInt_0_jsfc0lwq21(X60Qtmp_9);
  let X60Qtmp_8 = allocFixed(8);
  mem.copy(X60Qtmp_8, dollarQ_2_sysvq0asl(X60Qx_2), 8);
  let X60Qtmp_7 = allocFixed(8);
  mem.copy(X60Qtmp_7, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1952534014);
    mem.setU32((_o + 4), strlit_0_I6208868947491189530_tff8wodtr);
    return _o;
  })(), X60Qtmp_8), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_7);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_15 = allocFixed(4);
  mem.copy(X60Qtmp_15, toJs_3_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1970238206);
    mem.setU32((_o + 4), strlit_0_I12805258542531914732_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qtmp_14 = allocFixed(8);
  mem.copy(X60Qtmp_14, toStr_0_jsfc0lwq21(X60Qtmp_15), 8);
  let X60Qtmp_13 = allocFixed(8);
  mem.copy(X60Qtmp_13, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1667326718);
    mem.setU32((_o + 4), strlit_0_I15421062535947656287_tff8wodtr);
    return _o;
  })(), X60Qtmp_14), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_13);
  write_7_syn1lfpjv(stdout, 10);
  mem.copy(o_0_tff8wodtr, newJsObject_0_jsfc0lwq21(), 4);
  let X60Qtmp_16 = allocFixed(4);
  mem.copy(X60Qtmp_16, toJs_3_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1835626238);
    mem.setU32((_o + 4), strlit_0_I834269026986168554_tff8wodtr);
    return _o;
  })()), 4);
  set_0_jsfc0lwq21(o_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1835101950);
    mem.setU32((_o + 4), strlit_0_I407209193152762291_tff8wodtr);
    return _o;
  })(), X60Qtmp_16);
  let X60Qtmp_17 = allocFixed(4);
  mem.copy(X60Qtmp_17, toJs_0_jsfc0lwq21(2026), 4);
  set_0_jsfc0lwq21(o_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1634040318);
    mem.setU32((_o + 4), strlit_0_I6393444175955872624_tff8wodtr);
    return _o;
  })(), X60Qtmp_17);
  let X60Qtmp_20 = allocFixed(4);
  mem.copy(X60Qtmp_20, get_0_jsfc0lwq21(o_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1634040318);
    mem.setU32((_o + 4), strlit_0_I6393444175955872624_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qx_3 = toInt_0_jsfc0lwq21(X60Qtmp_20);
  let X60Qtmp_19 = allocFixed(8);
  mem.copy(X60Qtmp_19, dollarQ_2_sysvq0asl(X60Qx_3), 8);
  let X60Qtmp_18 = allocFixed(8);
  mem.copy(X60Qtmp_18, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 2033086462);
    mem.setU32((_o + 4), strlit_0_I6644378417582681152_tff8wodtr);
    return _o;
  })(), X60Qtmp_19), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_18);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_23 = allocFixed(4);
  mem.copy(X60Qtmp_23, global_0_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1330858750);
    mem.setU32((_o + 4), strlit_0_I6373137695046429832_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qtmp_22 = allocFixed(4);
  mem.copy(X60Qtmp_22, call_1_jsfc0lwq21(X60Qtmp_23, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1920234494);
    mem.setU32((_o + 4), strlit_0_I7519307887382905868_tff8wodtr);
    return _o;
  })(), o_0_tff8wodtr), 4);
  let X60Qtmp_21 = allocFixed(8);
  mem.copy(X60Qtmp_21, toStr_0_jsfc0lwq21(X60Qtmp_22), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_21);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_24 = allocFixed(4);
  mem.copy(X60Qtmp_24, toJs_2_jsfc0lwq21(true), 4);
  let X60Qx_4 = toBool_0_jsfc0lwq21(X60Qtmp_24);
  let X60Qdesugar_0 = allocFixed(8);
  mem.copy(X60Qdesugar_0, dollarQ_3_sysvq0asl(X60Qx_4), 8);
  let X60Qtmp_25 = allocFixed(4);
  mem.copy(X60Qtmp_25, toJs_2_jsfc0lwq21(false), 4);
  let X60Qx_5 = toBool_0_jsfc0lwq21(X60Qtmp_25);
  let X60Qdesugar_1 = allocFixed(8);
  mem.copy(X60Qdesugar_1, dollarQ_3_sysvq0asl(X60Qx_5), 8);
  let X60Qx_6 = len_4_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1869570814);
    mem.setU32((_o + 4), strlit_0_I14551632781070332322_tff8wodtr);
    return _o;
  })());
  let X60Qx_7 = len_4_sysvq0asl(X60Qdesugar_0);
  let X60Qx_8 = len_4_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 8193);
    mem.setU32((_o + 4), 0);
    return _o;
  })());
  let X60Qx_9 = len_4_sysvq0asl(X60Qdesugar_1);
  let X60Qdesugar_2 = allocFixed(8);
  mem.copy(X60Qdesugar_2, newStringOfCap_0_sysvq0asl((((X60Qx_6 + X60Qx_7) + X60Qx_8) + X60Qx_9)), 8);
  add_2_sysvq0asl(X60Qdesugar_2, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1869570814);
    mem.setU32((_o + 4), strlit_0_I14551632781070332322_tff8wodtr);
    return _o;
  })());
  add_2_sysvq0asl(X60Qdesugar_2, X60Qdesugar_0);
  add_2_sysvq0asl(X60Qdesugar_2, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 8193);
    mem.setU32((_o + 4), 0);
    return _o;
  })());
  add_2_sysvq0asl(X60Qdesugar_2, X60Qdesugar_1);
  write_0_syn1lfpjv(stdout, X60Qdesugar_2);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_28 = allocFixed(4);
  mem.copy(X60Qtmp_28, get_0_jsfc0lwq21(o_0_tff8wodtr, (() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1886351102);
    mem.setU32((_o + 4), strlit_0_I933664836153361417_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qx_10 = isNil_0_jsfc0lwq21(X60Qtmp_28);
  let X60Qtmp_27 = allocFixed(8);
  mem.copy(X60Qtmp_27, dollarQ_3_sysvq0asl(X60Qx_10), 8);
  let X60Qtmp_26 = allocFixed(8);
  mem.copy(X60Qtmp_26, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1936289278);
    mem.setU32((_o + 4), strlit_0_I6074055191300679588_tff8wodtr);
    return _o;
  })(), X60Qtmp_27), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_26);
  write_7_syn1lfpjv(stdout, 10);
  let X60Qtmp_31 = allocFixed(4);
  mem.copy(X60Qtmp_31, global_0_jsfc0lwq21((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1952534014);
    mem.setU32((_o + 4), strlit_0_I12935728853510326435_tff8wodtr);
    return _o;
  })()), 4);
  let X60Qx_11 = eqQ_0_jsfc0lwq21(m_0_tff8wodtr, X60Qtmp_31);
  let X60Qtmp_30 = allocFixed(8);
  mem.copy(X60Qtmp_30, dollarQ_3_sysvq0asl(X60Qx_11), 8);
  let X60Qtmp_29 = allocFixed(8);
  mem.copy(X60Qtmp_29, ampQ_0_sysvq0asl((() => {
    let _o = allocFixed(8);
    mem.setU32(_o, 1818588158);
    mem.setU32((_o + 4), strlit_0_I11663264536865316071_tff8wodtr);
    return _o;
  })(), X60Qtmp_30), 8);
  write_0_syn1lfpjv(stdout, X60Qtmp_29);
  write_7_syn1lfpjv(stdout, 10);
  nimStrDestroy(X60Qtmp_29);
  nimStrDestroy(X60Qtmp_30);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_31);
  nimStrDestroy(X60Qtmp_26);
  nimStrDestroy(X60Qtmp_27);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_28);
  nimStrDestroy(X60Qdesugar_2);
  nimStrDestroy(X60Qdesugar_1);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_25);
  nimStrDestroy(X60Qdesugar_0);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_24);
  nimStrDestroy(X60Qtmp_21);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_22);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_23);
  nimStrDestroy(X60Qtmp_18);
  nimStrDestroy(X60Qtmp_19);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_20);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_17);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_16);
  nimStrDestroy(X60Qtmp_13);
  nimStrDestroy(X60Qtmp_14);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_15);
  nimStrDestroy(X60Qtmp_7);
  nimStrDestroy(X60Qtmp_8);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_9);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_12);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_11);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_10);
  nimStrDestroy(X60Qtmp_2);
  nimStrDestroy(X60Qtmp_3);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_4);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_6);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_5);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_0);
  eQdestroy_0_jsfc0lwq21(X60Qtmp_1);
}

let cmdCount = allocFixed(4);

let cmdLine = allocFixed(4);

let nimEnviron = allocFixed(4);

function main(X60Qargc_0_tff8wodtr, X60Qargv_0_tff8wodtr, X60Qenvp_0_tff8wodtr) {
  mem.setI32(cmdCount, X60Qargc_0_tff8wodtr);
  mem.setU32(cmdLine, X60Qargv_0_tff8wodtr);
  mem.setU32(nimEnviron, X60Qenvp_0_tff8wodtr);
  X60Qini_0_tff8wodtr();
  nimFlushStdStreams();
  return 0;
}
